### ISSUE TITLE
does it support  AP channel tracknig ?! 

### ISSUE THREAD

**Issue by minanagehsalalma** [mayankmetha/EVILTWIN#1]
?

**Comment by mayankmetha** [comment]
No. AP channel has to be entered manually. There is no support yet for AP Channel tracking.

**Comment by minanagehsalalma** [comment]
@mayankmetha  why ?....   fluxion have  added it by the way .... but it  have unsolved bugs in the check page.php and no body knows why !

**Comment by mayankmetha** [comment]
This isn't fluxion.

**Comment by minanagehsalalma** [comment]
@mayankmetha  so is it better ?
